### ISSUE TITLE
Add licensing information

### ISSUE THREAD

**Issue by azonenberg** [glscopeclient/scopehal-sigrok-bridge#1]
There's no license information in the repo now so it's hard for people to actually use it.

I assume what makes the most sense is for the source to be dual licensed under 3-clause BSD like the rest of the glscopeclient project (so we can pull source from the repo into other parts of the project should the need arise), plus whatever GPL version sigrok uses. Binaries which then link to sigrok will be covered under GPL.

**Comment by 602p** [comment]
I'll go ahead and add the following as a `LICENSE` file unless there's a more correct/formal phrasing:
```
This software is dual licensed under either the BSD 3-Clause License, or -- to whatever extent is required as a result of linking against libsigrok (or libsigrok4DSL) -- version 3 of the GNU General Public License. Both licenses are reproduced below:

BSD 3-Clause License:
 -- SNIP --

GNU GPL v3:
 -- SNIP --

```

**Comment by azonenberg** [comment]
Sounds good.
